name: Pylint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install .
    - name: Analysing tools with pylint
      run: |
        pylint tools
    - name: Analysing problems with pylint (no docs required)
      run: |
        pylint --disable=C0116,C0115,C0114,C0209 aoc2019 aoc2020
        pylint --disable=C0116,C0115,C0114 aoc2021
